/*
  # Create Project Previews Storage Bucket

  ## Overview
  This migration creates a storage bucket for project preview images (thumbnails).
  Previews are automatically captured every 60 seconds and stored here.

  ## Storage Bucket

  ### `project-previews`
  Stores project preview images:
  - Public read access (for displaying thumbnails)
  - User-specific write access (users can only upload to their own folder)
  - Automatic cleanup of old previews
  - Max file size: 5MB per preview

  ## Structure
  Files are organized as: `{user_id}/{project_id}/preview_{project_id}_{timestamp}.png`

  ## Security

  ### Policies
  - Anyone can view preview images (public read)
  - Authenticated users can upload to their own user folder
  - Users can update/delete their own preview images
  - File size limited to 5MB
  - Only PNG images allowed

  ## Important Notes
  1. Preview images are automatically generated by the auto-backup service
  2. Old previews are automatically deleted when new ones are uploaded
  3. Public URL is stored in projects.thumbnail field
  4. For guest users, previews are stored in localStorage/IndexedDB
*/

-- Create storage bucket for project previews
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
  'project-previews',
  'project-previews',
  true,
  5242880, -- 5MB limit
  ARRAY['image/png', 'image/jpeg']
)
ON CONFLICT (id) DO NOTHING;

-- Policy: Allow public read access to preview images
CREATE POLICY "Public read access for previews"
  ON storage.objects
  FOR SELECT
  TO public
  USING (bucket_id = 'project-previews');

-- Policy: Allow authenticated users to upload to their own folder
CREATE POLICY "Users can upload own previews"
  ON storage.objects
  FOR INSERT
  TO authenticated
  WITH CHECK (
    bucket_id = 'project-previews' AND
    (storage.foldername(name))[1] = auth.uid()::text
  );

-- Policy: Allow users to update their own previews
CREATE POLICY "Users can update own previews"
  ON storage.objects
  FOR UPDATE
  TO authenticated
  USING (
    bucket_id = 'project-previews' AND
    (storage.foldername(name))[1] = auth.uid()::text
  )
  WITH CHECK (
    bucket_id = 'project-previews' AND
    (storage.foldername(name))[1] = auth.uid()::text
  );

-- Policy: Allow users to delete their own previews
CREATE POLICY "Users can delete own previews"
  ON storage.objects
  FOR DELETE
  TO authenticated
  USING (
    bucket_id = 'project-previews' AND
    (storage.foldername(name))[1] = auth.uid()::text
  );
